[package]
name = "envoy-proxy-dynamic-modules-rust-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Envoy Proxy Authors <envoy-dev@googlegroups.com>"]
description = "Envoy Proxy Dynamic Modules Rust SDK"
license = "Apache-2.0"
repository = "https://github.com/envoyproxy/envoy"

[dependencies]
mockall = "0.13.1"

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", rev = "ccd563767ab1509f7c0eb68c6effc79eaf3684a9" }

[lib]
