[package]
name = "envoy-proxy-dynamic-modules-rust-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Envoy Proxy Authors <envoy-dev@googlegroups.com>"]
description = "Envoy Proxy Dynamic Modules Rust SDK"
license = "Apache-2.0"
repository = "https://github.com/envoyproxy/envoy"

[dependencies]
mockall = "0.13.1"

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", rev = "74a5f30c14769891e12de53ba275233ef2616819" }

[lib]
